import Head from 'next/head';
import Image from 'next/image';
import { Geist, Geist_Mono } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <div className={styles.nav}>
          <div className={styles.logo}>
            <Image src='/logo.svg' alt='Logo' width={150} height={48} />
          </div>
          <div className={styles.links}>
            <div className={styles.navlink}>Products</div>
            <div className={styles.navlink}>Solutions</div>
            <div className={styles.navlink}>Resources</div>
            <div className={styles.navlink}>Enterprise</div>
            <div className={styles.navlink}>Pricing</div>
            <div className={styles.navlink}>Sign In</div>
            <div className={styles.navButtonPrimary}>Get Loom for Free</div>
            <div className={styles.navButtonSecondary}>Contact Sales</div>
          </div>
        </div>
        <main className={styles.main}>
          <div className={styles.section1}>
            <div className={styles.quote}>
              One video is worth a thousand words
            </div>
            <div className={styles.description}>
              Easily record and share AI-powered video messages with your
              teammates and customers to supercharge productivity
            </div>
            <div className={styles.buttons}>
              <div className={styles.buttonPrimary}>Get Loom for Free</div>
              <a className={styles.buttonSecondary}>Install Chrome Extension</a>
            </div>
            <div className={styles.video}>
              <video className={styles.videoPlayer} controls>
                <source src='rickroll.mp4' type='video/mp4' />
                Your browser does not support the video tag.
              </video>
            </div>
          </div>
          <div className={styles.section2}>
            <div className={styles.companies}>
              <div className={styles.trust}>
                Millions of people across 400,000 companies choose Loom
              </div>
              <div className={styles.buttonPrimary2}>Get Loom for Free</div>
            </div>
          </div>
        </main>
        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
